name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
      - name: Test
        run: |
          go test -v ./...
      - name: Goa Example Test
        run: |
          cd goa && make goa_gen &&make test
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: goa gen
          branch: ${{ github.head_ref }}
      - name: GraphQL Example Test
        run: |
          cd ./graphql/testdata/gqlgen-todos && go test ./...
          
