name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go 1.x
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
      - name: Build
        run: go mod tidy && go build -v ./...
      - name: Test
        run: |
          go test -v ./...
      - name: Goa Example Test
        run: |
          cd goa && make goa_gen &&make test
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: goa gen
          branch: ${{ github.head_ref }}
      - name: GraphQL Example Test
        run: |
          cd ./graphql/testdata/gqlgen-todos && go mod tidy && go test ./...
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: go mod tidy
          branch: ${{ github.head_ref }}
